### ISSUE TITLE
Wrapper to Panel connection issue?

### ISSUE THREAD

**Issue by Kei-Shin** [TunkDesign/NeMa#42]
I cant seem to access the wrapper while on the dashboard it says the wrapper is online but upon selecting a server it states in the pop up "connection lost" before moving to "Still connecting"  with a new pop up replacing the old one. In the background below the files tab of the server it has a error briefly shown labeled "Error: undefined" 
![nemanager error](https://cloud.githubusercontent.com/assets/22483737/19415151/3f5d39a6-9335-11e6-8d83-dd3755eba4a8.png)

**Comment by hammondb4** [comment]
I have the same error. I can create the wrapper and in the wrapper console in my desktop I see when I create the server via online panel. When I try to connect from the dashboard pop up shows "Still connecting" and that's all. Connection it's not a problem because the wrapper is really connected. Maybe we need to redirect another port?
