### ISSUE TITLE
Constant Python Error in Wrapper Window

### ISSUE THREAD

**Issue by Breadcrust** [TunkDesign/NeMa#53]
Constantly my wrapper window is updating with 

```
Traceback (most recent call last):
  File "c:\Program Files\Python27\lib\logging\handlers.py", line 77, in emit
  File "c:\Program Files\Python27\lib\logging\handlers.py", line 151, in shouldRollover
  File "C:\TunkDesign\Build\NeMa\build\NeMa\out00-PYZ.pyz\codecs", line 703, in seek
ValueError: I/O operation on closed file
Logged from file logging, line 1554
```

My log states:

`[1554 | ERROR | 30/01/2017 08:42:37 AM] Received invalid status response packet.
[1554 | ERROR | 30/01/2017 08:42:37 AM] Received invalid JSON.`

This issue has only come to light since updating to 2.2, I am using Windows Server 2016 but this bug is also present on Windows 10.

**Comment by TunkDesign** [comment]
The traceback you're seeing is the wrapper failing to write to the log file. This usually happens when the wrapper either doesn't have permission to write to the log file or something else is using/reading it. This is almost always fixed by running NeManager as an administrator!

The log error you're seeing is related to something completely different though. That error belongs to the internal pinger, which receives ping data from a server.

If this still happens after running it as an administrator, please let me know and reopen this issue. Thanks :)

PS; Sorry for the VERY late response.
