### ISSUE TITLE
CSRF won't let me do anything

### ISSUE THREAD

**Issue by InfinityOfficialNetwork** [TunkDesign/NeMa#63]
This is the ***worst*** designed website on the ***planet***, I have to use the ***freaking tor browser*** just to log in, ***nothing*** will work, please ***fix soon.***
UPDATE 001: ***No one*** has fixed this ***"website"*** and it is still broken
UPDATE 002: For any one that asks, I am using ***Microsoft Edge***, not ***Internet Explorer***

**Comment by TunkDesign** [comment]
Hey there!

I'm sorry that you think that, but I will look into it. I only just got this notification, so no-one has even had the time to look into it yet.

I think that Microsoft Edge might have been overlooked during development, due to system administrators usually use something else! However that's not a valid excuse! I'll see what we can do!
